version: '2'

services:
  fastapi_exporter:
    container_name: fastapi_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    depends_on:
      - fastapi_exporter
